# GitHub Action for generating a contribution graph with a snake eating your contributions.

# ![snake gif](https://github.com/your-user-name/your-user-name/blob/output/github-contribution-grid-snake.gif)

# GitHub Action para gerar uma animação de cobrinha consumindo suas contribuições.

# GitHub Action para gerar uma animação de cobrinha consumindo suas contribuições.

name: Generate Snake  # Nome do workflow

# Define quando a ação será executada.
on:
  schedule:
    # Roda a cada 12 horas
    - cron: "0 */12 * * *"
  
  # Permite executar o workflow manualmente a partir da aba Actions
  workflow_dispatch: 
  
  # Executa o workflow em cada push na branch 'main'
  push:
    branches:
      - main

# A sequência de execuções neste workflow:
jobs:
  # Este workflow contém um único job chamado "build"
  build:
    # Tipo de runner que o job irá utilizar
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas a serem executadas como parte do job
    steps:
      # Etapa para clonar o repositório
      - name: Clone repo
        uses: actions/checkout@v3  # Usando a ação oficial do GitHub para clonar o repositório
    
      # Etapa para gerar os arquivos da cobrinha na pasta './dist/'
      - name: Generate the snake files in './dist/'
        uses: Platane/snk@v3  # Usando a ação do Platane para gerar a animação
        id: snake-gif  # ID para referenciar esta etapa posteriormente
        with:
          github_user_name: ${{ github.repository_owner }}  # Usa o nome do proprietário do repositório
          outputs: |     
            dist/github-contribution-grid-snake.gif  # Saída do arquivo GIF da cobrinha
            dist/github-contribution-grid-snake.svg  # Saída do arquivo SVG da cobrinha
          theme: dark  # Define o tema da animação como escuro
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação para acessar o repositório

      # Etapa para mostrar o status do build
      - name: Show build status
        run: git status  # Executa o comando para mostrar o status do git

      # Etapa para enviar os novos arquivos para a branch 'output'
      - name: Push new files to the output branch
        uses: crazy-max/ghaction-github-pages@v3.1.0  # Usando ação para enviar arquivos para GitHub Pages
        with:
          target_branch: output  # Branch de destino onde os arquivos serão enviados
          build_dir: dist  # Diretório onde os arquivos gerados estão localizados
          commit_message: Update snake animations  # Mensagem do commit para registrar a atualização
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação para acessar o repositório

