name: Generate Snake Game

# Definindo gatilhos: schedule (cron) para rodar diariamente e workflow_dispatch para execução manual
on:
  schedule:
    - cron: "0 0 * * *"  # Isso vai rodar uma vez por dia (meia-noite UTC)
  workflow_dispatch:  # Permite que você inicie o workflow manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Baixar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Gerar a animação da cobrinha
      - name: Generate Snake Game
        uses: Platane/snk@master
        with:
          github_user_name: DevitaMaster  # Substitua pelo seu nome de usuário do GitHub
          outputs: dist/snake.svg

      # Publicar o arquivo gerado na branch `output`
      - name: Push Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # A animação será publicada na branch 'output'
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Usado para autenticar o push

