name: Generate Snake Game

on:
  schedule:
    - cron: "0 0 * * *"  # Roda diariamente à meia-noite UTC
  workflow_dispatch:  # Permite rodar manualmente

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Etapa para clonar o repositório
      - name: Check out the repository
        uses: actions/checkout@v2

      # Etapa para gerar a animação da cobrinha
      - name: Generate Snake Game
        uses: Platane/snk@v2.0.0
        with:
          github_user_name: DevitaMaster  # Nome do seu usuário do GitHub
          outputs: dist/snake.svg

      # Etapa para publicar a animação da cobrinha
      - name: Push Snake Game to the output branch
        uses: crazy-max/ghaction-github-pages@v2.1.3
        with:
          target_branch: output  # Publica na branch `output`
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Autenticação
