# GitHub Action para gerar um gráfico de contribuição com uma cobrinha comendo suas contribuições.

# ![snake gif](https://github.com/your-user-name/your-user-name/blob/output/github-contribution-grid-snake.gif)

name: Generate Snake  # Nome: Gerar Cobrinha

# Controla quando a ação será executada.
on:
  schedule:
      # a cada 12 horas
    - cron: "0 */12 * * *"

  # Este comando nos permite executar a Ação automaticamente na aba de Ações.
  workflow_dispatch: 
  
  # Também executa em cada push na branch principal
  push:
    branches:
    - main

# A sequência de execuções neste workflow:
jobs:
  # Este workflow contém um único job chamado "build"
  build:
    # O tipo de runner que o job irá utilizar
    runs-on: ubuntu-latest

    # As etapas representam uma sequência de tarefas que serão executadas como parte do job
    steps:
      - name: Clone repo  # Nome: Clonar repositório
        uses: actions/checkout@v3  # Usando a ação oficial do GitHub para clonar o repositório
    
      - name: Generate the snake files in './dist/'  # Nome: Gerar os arquivos da cobrinha na pasta './dist/'
        uses: Platane/snk@v3  # Usando a ação do Platane para gerar a animação
        id: snake-gif  # ID para referenciar esta etapa posteriormente
        with:
          github_user_name: ${{ github.repository_owner }}  # Usa o nome do proprietário do repositório
          outputs: |     
            dist/github-contribution-grid-snake.gif  # Saída do arquivo GIF da cobrinha
            dist/github-contribution-grid-snake.svg  # Saída do arquivo SVG da cobrinha
        env:
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Token de autenticação para acessar o repositório

      - name: Show build status  # Nome: Mostrar status do build
        run: git status  # Executa o comando para mostrar o status do git

  
